git:
  commitMessage: "Release of v${version}"
  requireCleanWorkingDir: false
github:
  release: true
  releaseName: "v${version}"
  assets:
    - dist/sif-*
hooks:
  before:git:release: "VERSION=${version} ./scripts/build.sh"